name: Java CI Workflow

# Trigger workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #  Checkout code from repository
    - name: Checkout Code
      uses: actions/checkout@v3

    #  Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    #  Cache Maven dependencies
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    #  Build the project using Maven
    - name: Build with Maven
      run: mvn clean install

    #  Run unit and integration tests
    - name: Run Tests
      run: mvn test
