name: Java CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Navigate to Project Directory
      run: cd WorkLog # Update this path if your project folder is named differently

    - name: Build with Maven
      run: mvn clean install
      working-directory: WorkLog # Specify the correct directory where `pom.xml` is located

    - name: Run Tests
      run: mvn test
      working-directory: WorkLog
